version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: configmanager-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=ConfigManager123!
      - MSSQL_PID=Express
    ports:
      - "1434:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - configmanager-network

  mongo:
    image: mongo:7.0
    container_name: configmanager-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=ConfigManager123!
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - configmanager-network

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: configmanager-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=ConfigManager123!
    ports:
      - "5673:5672"    # AMQP port
      - "15673:15672"  # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - configmanager-network

volumes:
  sqlserver_data:
  mongo_data:
  rabbitmq_data:

networks:
  configmanager-network:
    driver: bridge
