global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Configuration Manager API
  - job_name: 'configmanager-api'
    static_configs:
      - targets: ['api:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Configuration Manager Blazor App
  - job_name: 'configmanager-blazorapp'
    static_configs:
      - targets: ['blazorapp:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s
    scrape_timeout: 10s

  # SQL Server (if metrics are exposed)
  - job_name: 'sqlserver'
    static_configs:
      - targets: ['sql-server:1433']
    scrape_interval: 60s
    scrape_timeout: 30s

  # MongoDB (if metrics are exposed)
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongo:27017']
    scrape_interval: 60s
    scrape_timeout: 30s

  # RabbitMQ Management API
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']
    metrics_path: '/api/metrics'
    scrape_interval: 60s
    scrape_timeout: 30s
    basic_auth:
      username: 'admin'
      password: 'ConfigManager123!'
